### ISSUE TITLE
wifi.send(unsigned int id, String) always returns TIMEOUT

### ISSUE THREAD

**Issue by madprogrammi** [Diaoul/arduino-ESP8266#22]
I'm trying to send a String through a multi-connection instance of the ESP8266 class. When I Serial.print(getStatus(wifi.send(id, sendable))); it returns "TIMEOUT" every time. The data is never received by the client. After defining the ESP8266_DEBUG macro, the serial output looks like:

```
AT+CIPSEND=0,7
busy
TIMEOUT
```

Where the first two lines are from the ESP8266 library, and TIMEOUT is the output of getStatus();. This code is run in a loop once the client sends a handshake, so I know that the link is up. Any ideas?

**Comment by Diaoul** [comment]
Use a longer timeout  with setTimeout. It defaults to 1s which may be too short.

**Comment by madprogrammi** [comment]
I had mine set at 3s. Does it need to be longer?

**Comment by taoyuan** [comment]
Which version of your esp8266 firmware ? We use 0.94.

**Comment by madprogrammi** [comment]
No idea - AT+GMR just responds "OK"

**Comment by taoyuan** [comment]
@madprogrammi Try [this](https://github.com/espressif/esp8266_at) firmware.
