### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by lholznagel** [Diaoul/arduino-ESP8266#25]
aHey,
first awesome Libary. The only Problem with the Libary is that there is no Documentation. A big Example is good and helpful but it would be nice to have a Documentation where I can read which Method makes what.

Greetz

**Comment by LFindanno** [comment]
Hallo, I found a good example at the end of page there is the link of full code. http://www.limpkin.fr/index.php?post/2014/12/07/First-Steps-with-the-ESP8266-03-Development-Board
byz
